#!/bin/bash
echo "Deploying stage dexter-budgeting"

docker pull ghcr.io/jsdexter/dexter-budgeting/client:latest
docker pull ghcr.io/jsdexter/dexter-budgeting/api:latest

docker container stop budget-client
docker container stop budget-api 
docker container rm budget-client
docker container rm budget-api 

docker run --name budget-client -p 3000:3000 -d ghcr.io/jsdexter/dexter-budgeting/client:latest
docker run --name budget-api -p 3070:3070 -d ghcr.io/jsdexter/dexter-budgeting/api:latest