#!/bin/bash
echo "Deploying stage dexter-budgeting"

cd ~/live/dexter-budgeting \
&& git checkout dev \
console.log("Deploy Step 1")
&& git pull \
console.log("Deploy Step 2")
&& npm i \
console.log("Deploy Step 3")
&& npm run build \
# && (pm2 stop dexter-budgeting_live || true) \
&& (docker stop dexter-budgeting_live || true) \
console.log("Deploy Step 4")
&& echo 'Installing:  done.' \
# && (pm2 delete dexter-budgeting_live || true) \
&& (docker delete dexter-budgeting_live || true) \
console.log("Deploy Step 5")
&& NODE_ENV=development pm2 --name dexter-budgeting_live start npm -- start \
&& echo "dexter-budgeting deployed successfully"