# # This is a basic workflow to help you get started with Actions

# name: Dexter Budgeting Builds

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Check out the repo
#         uses: actions/checkout@v2
        
#       - name: Log in to Docker Hub
#         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#         with:            
#            username: ${{ secrets.DOCKER_USERNAME }}
#            password: ${{ secrets.DOCKER_PASSWORD }}
           
#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with: 
#           images: jsdexter/budgeting-client

#       # Runs a single command using the runners shell
#       - name: docker build client
#         uses: docker/build-push-action@v2
#         with: 
#            repository: jsdexter/budgeting-client
#            dockerfile: client/Dockerfile
#            tags: latest
#       - name: docker build api
# #         run: |
# #           docker build ./api
#         uses: docker/build-push-action@v2
#         with: 
#            repository: jsdexter/budgeting-server
#            dockerfile: api/Dockerfile
#            tags: latest
           
name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }},ghcr.io/${{ github.repository }}:latest
          push: true
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
    
